const mongoose = require('mongoose');

const ProfileSchema = new mongoose.Schema({
  registration_no: { type: String, required: true, unique: true },
  registration_date: String,
  expiry_date: String,
  marital_status: String,
  first_name: String,
  last_name: String,
  gender: String,
  date_of_birth: String,
  age: Number,
  height: String,
  name_of_parent: String,
  address: String,
  country: String,
  state: String,
  city: String,
  pincode: String,
  mobile_no: String,
  email_id: String,
  educational_qualification: String,
  occupation: String,
  income_per_month: String,
  mother_tounge: String,
  religion: String,
  caste: String,
  gotra: String,
  rashi: String,
  from_age_preference: Number,
  to_age_preference: Number,
  from_height_preference: String,
  to_height_preference: String,
  education_preference: String,
  caste_preference: String,
  any_other_info: String,
  terms_conditions_status: String,
  status: String,
  type_of_user: String,
  profilefor: String,
  likes: String,
  current_status: String,
  refered_by: String,
  skin_type: String,
  body_type: String,
  diet: String,
  drink: String,
  smoke: String,
  sunsign: String,
  bloodgroup: String,
  mobile_verification: String,
  image_verification: String,
  secure_image: String,
  subcaste: String,
  brother_younger_unmarried: String,
  brother_younger_married: String,
  brother_elder_unmarried: String,
  brother_elder_married: String,
  sister_younger_unmarried: String,
  sister_younger_married: String,
  sister_elder_unmarried: String,
  sister_elder_married: String,
  occupation_country: String,
  occupation_country_preference: String,
  maritalstatus_preference: String,
  contactinfo: String,
  assistance: String,
  nakshatra: String,
  boost_profile: String,
  boosted_on: String
}, { collection: 'registration_tbl' }); // Specify your collection name here

module.exports = mongoose.model('Profile', ProfileSchema);